name: movie_cast_stacked
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #intl
  intl: ^0.17.0

  # Firebase
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0

  # Logger
  logger: ^1.0.0
  
  # Stacked
  stacked: ^2.1.7
  stacked_services: null

dev_dependencies:
  build_runner: ^2.0.4

  # linting
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: null

flutter:
  uses-material-design: true

# Assets Example
#  assets:
#    - assets/images/
#
# Fonts Example
#  fonts:
#    - family: Open Sans
#      fonts:
#        - asset: assets/fonts/OpenSans-Italic.ttf
#          style: italic
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/OpenSans-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/OpenSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/OpenSans-Regular.ttf
#          weight: 400
